Say-Better/Service-Server

.editorconfig
build.gradle
rule-config/naver-checkstyle-rules.xml
rule-config/naver-checkstyle-suppressions.xml
rule-config/naver-intellij-formatter.xml

- 2024/01/12
> 변경 사항
- java code convention 적용
- 
- 
- 
-
- close #1

[Feature-1] 코드 컨벤션 적용

---

src/main/java/com/aesp/domain/temp/application/TempService.java
src/main/java/com/aesp/domain/temp/converter/TempConverter.java
src/main/java/com/aesp/domain/temp/converter/TempResponseConverter.java
src/main/java/com/aesp/domain/temp/dao/impl/TempReadRepositoryImpl.java
src/main/java/com/aesp/domain/temp/dao/impl/TempWriteRepositoryImpl.java
src/main/java/com/aesp/domain/temp/dao/repository/TempRepository.java
src/main/java/com/aesp/domain/temp/domain/Temp.java
src/main/java/com/aesp/domain/temp/dto/TempRequest.java
src/main/java/com/aesp/domain/temp/dto/TempResponse.java
src/main/java/com/aesp/domain/temp/exception/TempException.java
src/main/java/com/aesp/domain/temp/ui/TempController.java

- 2024.01.13
> 변경 사항
- Domain에 대한 directory 구조 설계
- 구조
```cmd
├─domain
│  └─temp
│      ├─application
│      │  └─TempService.java
│      │
│      ├─converter
│      │  ├─TempConverter.java
│      │  └─TempResponseConverter.java
│      │
│      ├─dao
│      │  ├─impl
│      │  │  ├─TempReadRepositoryImpl.java
│      │  │  └─TempWriteRepositoryImpl.java
│      │  │
│      │  └─repository
│      │       └─TempRepository.java
│      │
│      ├─domain
│      │  └─Temp.java
│      │
│      ├─dto
│      │  ├─TempRequest.java
│      │  └─TempResponse.java
│      │
│      ├─exception
│      │  └─TempException.java
│      │
│      └─ui
│         └─TempController.java
```
| package명 | 기술 가이드 |
|:-------|:---------|
| application | 비즈니스와 관련된 로직을 처리한다. <br> 주로 Service layer 클래스들을 정의한다. |
| converter …

[Feature/3] Domain package 구조 적용

---

build.gradle
src/main/java/com/aesp/domain/temp/application/TempService.java
src/main/java/com/aesp/domain/temp/converter/TempResponseConverter.java
src/main/java/com/aesp/domain/temp/dto/TempResponse.java
src/main/java/com/aesp/domain/temp/exception/TempException.java
src/main/java/com/aesp/domain/temp/ui/TempController.java
src/main/java/com/aesp/global/common/code/status/ErrorStatus.java
src/main/java/com/aesp/global/common/exception/ExceptionAdvice.java
src/main/java/com/aesp/global/common/exception/GeneralException.java

- 2024 / 01 / 13
> 변경 사항
- Global Exception Handler 구현
- 테스트용 api 제작
- 성공하는 api
- 일부로 실패하는 api
- x
- x
- x
- x
- close #5

[Feature/5] 전역 예외처리 기능 구현

---

.github/workflows/CI_CD.yml
Dockerfile
build.gradle
src/main/java/com/saybetter/domain/solution/domain/Assign.java
src/main/java/com/saybetter/domain/solution/domain/constant/AssignStep.java
src/main/resources/application-dev-datasource.yml
src/main/resources/application-dev.yml
src/main/resources/application-local-datasource.yml
src/main/resources/application-local.yml
src/main/resources/application.yml

- 2024.02.17
> 변경 사항
- application 환경 구축 [local, dev]
- docker file 생성
- github action CI 구현
- x
- x
- x
- x
- close #14

[Feature/14] CI/CD 환경 구축

---

src/main/java/com/saybetter/domain/member/application/AuthFacade.java
src/main/java/com/saybetter/domain/member/application/MemberFacade.java
src/main/java/com/saybetter/domain/member/application/converter/ConnectConverter.java
src/main/java/com/saybetter/domain/member/application/impl/ConnectService.java
src/main/java/com/saybetter/domain/member/application/impl/MemberService.java
src/main/java/com/saybetter/domain/member/domain/Connect.java
src/main/java/com/saybetter/domain/member/ui/MemberController.java
src/main/java/com/saybetter/global/common/code/status/ErrorStatus.java
src/main/java/com/saybetter/global/config/security/SecurityConfig.java
src/main/java/com/saybetter/global/utils/CodeUtil.java
src/main/java/com/saybetter/global/utils/RedisUtil.java

- 2024.02.23
> 변경 사항
- 학습자 - 교육자 연결 코드 발급 기능 구현
- 학습자 - 교육자 연결 코드 인증 기능 구현
- x
- x
- x
- x
- close #22

[Feature/22] 학습자 교육자 연결 기능 구현

---

build.gradle
src/main/java/com/saybetter/SayBetterApplication.java
src/main/java/com/saybetter/client/api/RecommendApi.java
src/main/java/com/saybetter/client/api/RecommendClient.java
src/main/java/com/saybetter/client/api/dto/RecommendRequest.java
src/main/java/com/saybetter/client/api/dto/RecommendResponse.java
src/main/java/com/saybetter/client/api/dto/RecommendResult.java
src/main/java/com/saybetter/client/converter/RecommendResultConverter.java
src/main/java/com/saybetter/domain/solution/application/SolutionFacade.java
src/main/java/com/saybetter/domain/solution/application/converter/SolutionConverter.java
src/main/java/com/saybetter/domain/solution/application/converter/SolutionResponseConverter.java
src/main/java/com/saybetter/domain/solution/application/converter/SolutionSymbolConverter.java
src/main/java/com/saybetter/domain/solution/application/impl/SolutionService.java
src/main/java/com/saybetter/domain/solution/application/impl/SolutionSymbolService.java
src/main/java/com/saybetter/domain/solution/domain/Solution.java
src/main/java/com/saybetter/domain/solution/domain/SolutionSymbol.java
src/main/java/com/saybetter/domain/solution/ui/SolutionController.java
src/main/java/com/saybetter/domain/solution/ui/dto/SolutionRequest.java
src/main/java/com/saybetter/domain/solution/ui/dto/SolutionResponse.java
src/main/java/com/saybetter/domain/symbol/application/impl/SymbolService.java
src/main/java/com/saybetter/domain/symbol/dao/repository/SymbolReadRepository.java
src/main/java/com/saybetter/global/config/properties/PropertiesConfig.java
src/main/java/com/saybetter/global/config/web/OpenFeignConfig.java
src/main/resources/application-api.yml
src/main/resources/application.yml

- 2024.02.25
> 변경 사항
- ai 기반 심볼 추천 기능 구현
- 단순 심볼 검색 기능 구현
- 솔루션 작성 기능 구현
- x
- x
- x
- https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/
- https://mangkyu.tistory.com/278
- https://mangkyu.tistory.com/279
- https://brightstarit.tistory.com/m/46
- https://github.com/team-dodn/spring-boot-java-template/tree/main/clients/client-example
- close #24

[Feature/24] 솔루션 제작 기능 구현

---

core/core-api/build.gradle
core/core-api/src/main/kotlin/io/say/better/SayBetterApplication.kt
core/core-api/src/main/kotlin/io/say/better/global/auth/OAuthAttributes.kt
core/core-api/src/main/kotlin/io/say/better/global/auth/service/CustomOAuth2UserService.kt
core/core-api/src/main/kotlin/io/say/better/global/config/security/SecurityConfig.kt
core/core-api/src/main/kotlin/io/say/better/global/jwt/filter/JwtAuthenticationProcessingFilter.kt
core/core-api/src/main/kotlin/io/say/better/global/jwt/service/JwtService.kt
core/core-api/src/main/resources/auth.yml
settings.gradle
storage/storage-mysql/src/main/java/io/say/better/storage/mysql/domain/entity/Member.java

> 변경 사항 설명
- JWT 버전 마이그레이션 (jws: 0.9 ~ 0.11)
- user roleType
-
- close #39

[Feature/39] 구글 소셜 로그인 에러 해결

---

core/core-api/build.gradle
core/core-api/src/main/kotlin/io/say/better/domain/member/ui/MemberController.kt
core/core-api/src/main/kotlin/io/say/better/domain/solution/ui/SolutionController.kt
core/core-api/src/main/kotlin/io/say/better/global/common/exception/ExceptionAdvice.kt
core/core-api/src/main/kotlin/io/say/better/global/common/response/ResponseDto.kt
core/core-api/src/main/resources/application.yml
tests/api-docs/build.gradle
tests/api-docs/src/main/java/io/say/better/test/api/Main.java
tests/api-docs/src/main/kotlin/io/say/better/test/api/Main.kt
tests/api-docs/src/main/kotlin/io/say/better/test/api/member/AuthControllerTest.kt
tests/api-docs/src/main/kotlin/io/say/better/test/api/member/MemberControllerTest.kt
tests/api-docs/src/main/kotlin/io/say/better/test/api/review/ReviewControllerTest.kt
tests/api-docs/src/main/kotlin/io/say/better/test/api/solution/SolutionControllerTest.kt

> 변경 사항 설명
- tests 내 패키지명을 코틀린에 맞게 수정
- 컨트롤러 단위 테스트 작성
- 테스트 정상 동작을 위해 Feature 단계에서 코드 작성 시 생략했던 옵션 추가
- 테스트에 이용되는 외부 라이브러리 추가
- application.yml 수정
- close #42

[Feature/42] 컨트롤러 단위 테스트 작성 및 기존 코드 리팩토링

---

core/core-api/src/main/kotlin/io/say/better/domain/solution/application/SolutionFacade.kt
core/core-api/src/main/kotlin/io/say/better/domain/solution/ui/SolutionController.kt
core/core-api/src/main/kotlin/io/say/better/domain/solution/ui/dto/SolutionRequest.kt
tests/api-docs/build.gradle
tests/api-docs/src/test/kotlin/io/say/better/test/api/solution/SolutionInfoControllerTest.kt
tests/api-docs/src/test/kotlin/io/say/better/test/api/solution/SolutionRepositoryTest.kt

> 변경 사항 설명
- 솔루션 생성 API 추가
- 솔루션 API 관련 테스트 코드 추가
- 테스트 모듈 build.gradle 변경
- close #54

[Feature/54] 솔루션 생성 API

---

support/logging/build.gradle
support/logging/build.gradle.kts
support/monitoring/build.gradle
support/monitoring/build.gradle.kts

> 변경 사항 설명
- support 모듈 build.gradle → build.gradle.kts로 변경
- close #60

[Feature/60] support 모듈 build.gradle → build.gradle.kts로 변경

---

storage/storage-rabbitmq-kt/src/main/kotlin/io/say/better/storage/rabbitmq/config/MessageQueueConfig.kt

> 변경 사항 설명
- RabbitMQ queue auto-delete 설정 추가
-
- 
- 
-
- close #78

:bug: Bug: RabbitMQ queue auto-delete 설정 추가

---

.github/workflows/dev_deploy.yml

[CI/CD] github action 수정

---

.github/workflows/dev_deploy.yml

[feature/74] ci/cd 수정

---

core/core-api/src/main/kotlin/io/say/better/domain/member/application/AuthFacade.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/application/MemberFacade.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/application/converter/AuthResponseConverter.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/application/impl/EducatorService.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/application/impl/LeanerService.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/application/impl/LearnerService.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/application/impl/MemberService.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/ui/AuthController.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/ui/dto/AuthResponse.kt
core/core-api/src/main/kotlin/io/say/better/domain/solution/application/SolutionFacade.kt
core/core-api/src/test/kotlin/io/say/better/domain/member/ui/AuthControllerTest.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domain/entity/Educator.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domain/entity/Learner.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domain/entity/Member.kt

> 변경 사항 설명
- 소셜 로그인을 신청하는 appType에 따라 학습자 혹은 교육자를 생성해주는 로직 구현
- close #89

[Feature/89] 교육자, 학습자 생성 로직 구현

---

core/core-api/src/main/kotlin/io/say/better/global/auth/handler/OAuth2LoginFailureHandler.kt
core/core-api/src/main/kotlin/io/say/better/global/auth/handler/OAuth2LoginSuccessHandler.kt
core/core-api/src/main/kotlin/io/say/better/global/auth/service/CustomOAuth2UserService.kt
core/core-api/src/main/kotlin/io/say/better/global/config/security/SecurityConfig.kt

> 변경 사항 설명
- Swagger 접근 시 발생한 문제 해결
- 로그인 api로 리다이렉션 됨
- 403 에러 발생
- 더 이상 사용하지 않는 클래스 Deprecated 처리
- CustomOAuth2UserService
- OAuth2LoginSuccessHandler
- OAuth2LoginFailureHandler
- close #99

[Feature/99] SecurityConfig 수정

---

core/core-api/src/main/kotlin/io/say/better/global/config/web/CorsConfig.kt
core/core-api/src/main/resources/swagger.yml

> 변경 사항 설명
- 
-
- 
- 
-
- close #

:bug: Bub: Swagger cors

---

core/core-api/src/main/kotlin/io/say/better/SayBetterApplication.kt
core/core-api/src/main/kotlin/io/say/better/global/config/web/CorsConfig.kt
core/core-api/src/main/resources/swagger.yml

> 변경 사항 설명
- 
-
- 
- 
-
- close #

:bug: Bug: Swagger cors

---

core/core-api/src/main/kotlin/io/say/better/domain/member/application/MemberFacade.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/ui/MemberController.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/ui/dto/MemberResponse.kt
core/core-api/src/test/kotlin/io/say/better/domain/member/ui/MemberControllerTest.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domain/constant/Gender.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domain/entity/Educator.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domain/entity/Learner.kt

> 변경 사항 설명
- Role에 따른 필요 정보 속성 추가
- Educator: 프로필 URL 추가
- Learner: 나이, 성별, 프로필 URL 추가 및 성별 추가에 따른 Gender Enum 클래스 생성
- Educator 및 Learner 회원 정보 조회 api 및 컨트롤러 테스트 작성
- close #106

[Feature/106] 프로필 정보 반환 Controller 생성

---

storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domain/constant/ReactionType.kt

> 변경 사항 설명
- ReactionType 클래스 속성 값 오탈자 수정
- close #110

:bug: Bug - ReactionType 클래스 속성 값 오탈자 수정

---

core/core-api/build.gradle.kts
core/core-api/src/main/kotlin/io/say/better/domain/member/application/MemberFacade.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/application/impl/EducatorService.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/application/impl/LearnerService.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/ui/MemberController.kt
core/core-api/src/main/resources/application.yml
core/core-api/src/test/kotlin/io/say/better/domain/member/ui/MemberControllerTest.kt
core/core-infra/build.gradle.kts
core/core-infra/src/main/kotlin/io/say/better/core/infra/config/S3Config.kt
core/core-infra/src/main/kotlin/io/say/better/core/infra/enums/AwsS3Folder.kt
core/core-infra/src/main/kotlin/io/say/better/core/infra/service/AwsS3Service.kt
core/core-infra/src/main/resources/infra.yml
settings.gradle.kts
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domain/entity/Educator.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domain/entity/Learner.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domain/entity/Member.kt

> 변경 사항 설명
- core-infra 모듈 추가
- core-infra 모듈 내에 AwsS3Service 추가 (파일 업로드)
- 초기정보 입력 API 추가 (교육자 / 학습자)
- 초기정보 입력 API에 대한 테스트 코드 작성
- 테스트코드 맞게 작성했는지 중점으로 봐주세요
- multipart에 대한 테스트 작성 시 MockMultipartFile을 사용할 수 있다.
- 스웨거에 예시 값을 넣어주면 좋을듯 한데 방법 생각중
-
- close #109 #112

:sparkles: Feat: core-infra 모듈 추가 및 S3 업로드 기능 추가 + 유저 초기정보 입력 API (교육자, 학습자) 개발과 스웨거 문서 작성

---

core/core-api/src/main/kotlin/io/say/better/domain/member/application/MemberFacade.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/ui/MemberController.kt
core/core-api/src/test/kotlin/io/say/better/domain/member/ui/MemberControllerTest.kt

> 변경 사항 설명
- 교육자-학습자 연결 및 연결 코드 검사 API에 응답값 추가
-
- 
- 
-
- close #117

:sparkles: Feat: 교육자-학습자 연결 및 연결 코드 검사 API에 응답값 추가

---

core/core-api/src/main/kotlin/io/say/better/domain/member/application/MemberFacade.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/application/impl/LearnerService.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/ui/MemberController.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/ui/dto/MemberRequest.kt
core/core-api/src/test/kotlin/io/say/better/domain/member/ui/MemberControllerTest.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domain/entity/Learner.kt

> 변경 사항 설명
- 학습자 초기정보 입력 API에 생년원일과 성별을 추가
-
- 
- 
-
- close #119

:sparkles: Feat: 학습자 초기정보 입력 API에 생년원일과 성별을 추가

---

storage/storage-redis-kt/src/main/kotlin/io/say/better/storage/redis/RedisConfig.kt
storage/storage-redis-kt/src/main/resources/redis.yml

> 변경 사항 설명
- redis 설정 수정
- close #127

[Feature/127] redis 설정 수정

---

core/core-api/src/docs/asciidoc/leaner.adoc
core/core-api/src/main/kotlin/io/say/better/global/jwt/filter/JwtAuthenticationProcessingFilter.kt
core/core-api/src/main/resources/static/docs/index.html
core/core-common/src/main/kotlin/io/say/better/core/common/code/status/ErrorStatus.kt
storage/storage-redis-kt/src/main/kotlin/io/say/better/storage/redis/RedisUtil.kt

> 변경 사항 설명
- Redis Util getData 함수의 널 단언 연산자 제거 및 call 위치에서 Exception throw 하게 수정
- 학습자 코드 발급 API 문서 수정
-
- 
- 
-
- close #129

:bug: Bug: 학습자 코드 관련 API Null Pointer Exception 수정 및 학습자 코드 발급 API 문서 수정

---

core/core-api/src/main/kotlin/io/say/better/domain/member/application/MemberFacade.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/application/impl/EducatorService.kt
core/core-api/src/main/kotlin/io/say/better/domain/member/application/impl/LearnerService.kt

> 변경 사항 설명
- 학습자/교육자 초기정보 입력 API 누락 코드 수정
-
- 
- 
-
- close #

:bug: Bug: 초기정보 입력 API 코드 누락 수정

---

core/core-api/src/main/kotlin/io/say/better/domain/member/application/MemberFacade.kt
core/core-infra/src/main/kotlin/io/say/better/core/infra/service/AwsS3Service.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domains/account/entity/Educator.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domains/account/entity/Learner.kt

> 변경 사항 설명
- 유저 초기정보 입력 API name 저장 안되는 버그 수정
- API 로직 한번만 확인 부탁드립니다.
- 
- 
-
- close #133

유저 초기정보 입력 API name 저장 안되는 버그 수정

---

storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/common/converter/EnumAttributeConverter.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/common/utils/CodedEnumUtil.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domains/account/entity/Learner.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domains/account/type/Gender.kt

> 변경 사항 설명
- enum converter 구현
- gender에 대한 enum converter 적용
- close #136

[Feature/136] enum converter 구현

---

clients/client-api/src/main/kotlin/io/say/better/client/oauth/google/api/GoogleOauth2Api.kt
clients/client-api/src/main/kotlin/io/say/better/client/oauth/google/client/GoogleOauthClient.kt
core/core-common/src/main/kotlin/io/say/better/core/common/auth/info/GoogleOAuth2UserInfo.kt

> 변경 사항 설명
- verifyToken 메서드 응답 형식 수정
- GoogleOAuth2UserInfo 클래스 내 non-null 타입 수정
- close #138

:bug: Bug - 구글 로그인 오류 수정

---

core/core-api/src/docs/asciidoc/solution.adoc
core/core-api/src/main/kotlin/io/say/better/domain/review/application/impl/RecordService.kt
core/core-api/src/main/kotlin/io/say/better/domain/review/application/impl/ReviewService.kt
core/core-api/src/main/kotlin/io/say/better/domain/solution/application/SolutionFacade.kt
core/core-api/src/main/kotlin/io/say/better/domain/solution/application/converter/RecordConverter.kt
core/core-api/src/main/kotlin/io/say/better/domain/solution/ui/SolutionController.kt
core/core-api/src/main/resources/static/docs/index.html
core/core-api/src/test/kotlin/io/say/better/domain/solution/ui/SolutionControllerTest.kt
core/core-common/src/main/kotlin/io/say/better/core/common/code/status/ErrorStatus.kt
core/core-infra/src/main/kotlin/io/say/better/core/infra/enums/AwsS3Folder.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domains/review/entity/Record.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domains/review/repository/RecordReadRepository.kt
storage/storage-mysql-kt/src/main/kotlin/io/say/better/storage/mysql/domains/review/repository/ReviewReadRepository.kt

> 변경 사항 설명
- 솔루션 종료 시 음성 파일 업로드 API
- 
- 파일 업로드 및 URL DB 반영 확인 완료
- 
- 
- 
- close #133

:sparkles: Feat: 솔루션 종료 시 음성 파일 업로드 API

---

clients/client-api/src/main/kotlin/io/say/better/client/symbol/api/RecommendApi.kt
clients/client-api/src/main/kotlin/io/say/better/client/symbol/converter/RecommendResultConverter.kt
clients/client-api/src/main/kotlin/io/say/better/client/symbol/dto/RecommendResponse.kt

> 변경 사항 설명
- ML서버 추천 api 호출 시 응답 값을 객체로 바인딩하는 과정에서 발생하는 오류 수정
- close #142

:bug: Bug - 추천 API 오류 수정

---

core/core-api/src/main/kotlin/io/say/better/domain/chatting/ui/ChattingController.kt

> 변경 사항 설명
- 채팅 api의 메서드 타입을 POST로 수정
- close #144

:bug: Bug - 채팅 API 메서드 수정

---

core/core-api/src/test/kotlin/io/say/better/domain/chatting/ui/ChattingControllerTest.kt

> 변경 사항 설명
- 채팅 API 수정에 따른 docs 업데이트
- close #146

[Feature/146] 채팅 API 수정에 따른 docs 업데이트
